# Generated by Django 4.2.8 on 2024-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_tesk_detial_tesk_alter_tesk_name_tesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesk',
            name='User_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
