# Generated by Django 4.2.8 on 2024-09-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_alter_tesk_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesk',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
