# Generated by Django 4.2.8 on 2024-09-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_tesk_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesk',
            name='due_date',
            field=models.DateField(),
        ),
    ]
