# Generated by Django 4.2.8 on 2024-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_alter_tesk_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesk',
            name='due_date',
            field=models.DateField(),
        ),
    ]
