# Generated by Django 4.2.8 on 2024-09-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_alter_tesk_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesk',
            name='email_sent',
        ),
    ]
