# Generated by Django 4.2.8 on 2024-09-29 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0011_remove_tesk_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesk',
            name='user',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
