# Generated by Django 4.2.8 on 2024-05-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_tesk', models.TextField()),
                ('Detial_tesk', models.CharField(max_length=100)),
                ('Reminder_time', models.DateTimeField()),
                ('User_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
