# Generated by Django 4.2.8 on 2024-06-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_alter_tesk_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesk',
            old_name='Reminder_time',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='tesk',
            old_name='Detial_tesk',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='tesk',
            old_name='Name_tesk',
            new_name='task_name',
        ),
        migrations.RemoveField(
            model_name='tesk',
            name='User_email',
        ),
        migrations.AddField(
            model_name='tesk',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
